apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: kctech
  name: kctech
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: kctech
    spec:
      containers:
      - image: sravanik1818/kubesintegration:1.0
        name: kctech
        ports:
        - name: kctech
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: kctech
  labels:
    app: kctech
spec:
  selector:
    name: kctech
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
